AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  ExampleS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ParamProjectID}-example

Parameters:
  ParamProjectName:
    Type: String
  ParamProjectScope:
    Type: String
  ParamProjectID:
    Type: String
  ParamENV:
    Type: String

Outputs:
  ProjectID:
    Description: Project ID
    Value: !Ref ParamProjectID
