AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  ExampleS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ProjectID}-example

Parameters:
  ProjectScope:
    Type: String
  ProjectName:
    Type: String
  ProjectID:
    Type: String
  ENV:
    Type: String

Outputs:
  ProjectID:
    Description: Project ID
    Value: !Ref ProjectID
  ENV:
    Description: Environment ID
    Value: !Ref ENV
